### ISSUE TITLE
The server experienced an internal error

### ISSUE THREAD

**Issue by mdmappledev** [brandonweeks/acme-device-attest-demo#3]
Hello @brandonweeks  . Hope you are doing well.

> POST /acme/acme/challenge/OcCB9Ch6...

For the above request, we are getting 500 error code and from logs, we can see this: "**_The server experienced an internal error_**" 

> POST /acme/acme/order/f28xS.../finalize

and the next request fails with 400 error: "**_The request attempted to finalize an order that is not ready to be finalized_**"

We have attached the logs. This issue is a counter-part to another [issue](https://github.com/brandonweeks/acme-device-attest-demo/issues/2) previously raised by us. Kindly help with troubleshooting the issue. 

[step.log](https://github.com/brandonweeks/acme-device-attest-demo/files/9452686/step.log)

**Comment by jessepeterson** [comment]
I'm way out of my league here, but based on the log (and our Slack chat) my interpretation is this:

1. The ACME account and order are setup okay.
2. The device tries to send the challenge response.
3. The parsing/interpreting of this challenge fails (`error unmarshalling CBOR`, `error validating challenge`)
4. Because the challenge was never satisfied the 'order' was never "finalized" and thus no certificate was returned.

I don't know why step 3 failed above. But the error I think is here:

https://github.com/brandonweeks/step-ca/blob/274f6ccb4186958e3b1e8ad50d3acd2eca20235b/acme/challenge.go#L456

I assume you have both `HardwareBound` and `Attest` set to True in your ACME profile payload?

**Comment by mdmappledev** [comment]
Thanks @jessepeterson 
We were sending out a lot of different payload combinations and didn't notice that the `Attest` was set to false. Once we changed it true, the profile worked fine.
